// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vehicle.proto
#ifndef GRPC_vehicle_2eproto__INCLUDED
#define GRPC_vehicle_2eproto__INCLUDED

#include "vehicle.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vehicle {

class Vehicle final {
 public:
  static constexpr char const* service_full_name() {
    return "vehicle.Vehicle";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::vehicle::VehicleModel* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::VehicleModel>> AsyncGetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::VehicleModel>>(AsyncGetVehicleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::VehicleModel>> PrepareAsyncGetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::VehicleModel>>(PrepareAsyncGetVehicleRaw(context, request, cq));
    }
    virtual ::grpc::Status GetAll(::grpc::ClientContext* context, const ::vehicle::Request& request, ::vehicle::QueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::QueryResponse>> AsyncGetAll(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::QueryResponse>>(AsyncGetAllRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::QueryResponse>> PrepareAsyncGetAll(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::QueryResponse>>(PrepareAsyncGetAllRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest* request, ::vehicle::VehicleModel* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest* request, ::vehicle::VehicleModel* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetAll(::grpc::ClientContext* context, const ::vehicle::Request* request, ::vehicle::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAll(::grpc::ClientContext* context, const ::vehicle::Request* request, ::vehicle::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::VehicleModel>* AsyncGetVehicleRaw(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::VehicleModel>* PrepareAsyncGetVehicleRaw(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::QueryResponse>* AsyncGetAllRaw(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle::QueryResponse>* PrepareAsyncGetAllRaw(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::vehicle::VehicleModel* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::VehicleModel>> AsyncGetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::VehicleModel>>(AsyncGetVehicleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::VehicleModel>> PrepareAsyncGetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::VehicleModel>>(PrepareAsyncGetVehicleRaw(context, request, cq));
    }
    ::grpc::Status GetAll(::grpc::ClientContext* context, const ::vehicle::Request& request, ::vehicle::QueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::QueryResponse>> AsyncGetAll(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::QueryResponse>>(AsyncGetAllRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::QueryResponse>> PrepareAsyncGetAll(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle::QueryResponse>>(PrepareAsyncGetAllRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest* request, ::vehicle::VehicleModel* response, std::function<void(::grpc::Status)>) override;
      void GetVehicle(::grpc::ClientContext* context, const ::vehicle::SingleRequest* request, ::vehicle::VehicleModel* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetAll(::grpc::ClientContext* context, const ::vehicle::Request* request, ::vehicle::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      void GetAll(::grpc::ClientContext* context, const ::vehicle::Request* request, ::vehicle::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vehicle::VehicleModel>* AsyncGetVehicleRaw(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::VehicleModel>* PrepareAsyncGetVehicleRaw(::grpc::ClientContext* context, const ::vehicle::SingleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::QueryResponse>* AsyncGetAllRaw(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle::QueryResponse>* PrepareAsyncGetAllRaw(::grpc::ClientContext* context, const ::vehicle::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetVehicle_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAll_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetVehicle(::grpc::ServerContext* context, const ::vehicle::SingleRequest* request, ::vehicle::VehicleModel* response);
    virtual ::grpc::Status GetAll(::grpc::ServerContext* context, const ::vehicle::Request* request, ::vehicle::QueryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVehicle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetVehicle() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetVehicle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVehicle(::grpc::ServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVehicle(::grpc::ServerContext* context, ::vehicle::SingleRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle::VehicleModel>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAll : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAll() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetAll() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAll(::grpc::ServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAll(::grpc::ServerContext* context, ::vehicle::Request* request, ::grpc::ServerAsyncResponseWriter< ::vehicle::QueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetVehicle<WithAsyncMethod_GetAll<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetVehicle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetVehicle() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle::SingleRequest, ::vehicle::VehicleModel>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle::SingleRequest* request, ::vehicle::VehicleModel* response) { return this->GetVehicle(context, request, response); }));}
    void SetMessageAllocatorFor_GetVehicle(
        ::grpc::MessageAllocator< ::vehicle::SingleRequest, ::vehicle::VehicleModel>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle::SingleRequest, ::vehicle::VehicleModel>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetVehicle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVehicle(::grpc::ServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVehicle(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetAll : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAll() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle::Request, ::vehicle::QueryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle::Request* request, ::vehicle::QueryResponse* response) { return this->GetAll(context, request, response); }));}
    void SetMessageAllocatorFor_GetAll(
        ::grpc::MessageAllocator< ::vehicle::Request, ::vehicle::QueryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle::Request, ::vehicle::QueryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAll() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAll(::grpc::ServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAll(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetVehicle<WithCallbackMethod_GetAll<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetVehicle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetVehicle() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetVehicle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVehicle(::grpc::ServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAll : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAll() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetAll() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAll(::grpc::ServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetVehicle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetVehicle() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetVehicle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVehicle(::grpc::ServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVehicle(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAll : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAll() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetAll() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAll(::grpc::ServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAll(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetVehicle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetVehicle() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetVehicle(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetVehicle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVehicle(::grpc::ServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVehicle(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAll : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAll() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAll(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAll() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAll(::grpc::ServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAll(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetVehicle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetVehicle() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle::SingleRequest, ::vehicle::VehicleModel>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle::SingleRequest, ::vehicle::VehicleModel>* streamer) {
                       return this->StreamedGetVehicle(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetVehicle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetVehicle(::grpc::ServerContext* /*context*/, const ::vehicle::SingleRequest* /*request*/, ::vehicle::VehicleModel* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetVehicle(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle::SingleRequest,::vehicle::VehicleModel>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAll : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAll() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle::Request, ::vehicle::QueryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle::Request, ::vehicle::QueryResponse>* streamer) {
                       return this->StreamedGetAll(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAll() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAll(::grpc::ServerContext* /*context*/, const ::vehicle::Request* /*request*/, ::vehicle::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAll(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle::Request,::vehicle::QueryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetVehicle<WithStreamedUnaryMethod_GetAll<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetVehicle<WithStreamedUnaryMethod_GetAll<Service > > StreamedService;
};

}  // namespace vehicle


#endif  // GRPC_vehicle_2eproto__INCLUDED
